inpath:  'C:\Users\PC\Desktop\POKUS_ivecor\Databaza\'         #where input wave data exist
outpath: 'C:\Users\PC\Desktop\POKUS_ivecor\vystup\' #where the program outputs exist

#features configuration
features:
  - vad #voice-activity-dectection
  - energy #log-energy
  - cep #cepstral coefficients
  - fb #filter-banks
  -
cepstral_coefficients: 19
filter_bank: log
filter_bank_size: 24
lower_frequency: 300
higher_frequency: 3400
vad: snr #can be either "energy", "snr"
snr_ratio: 40
window_size: 0.025 #in seconds (25 milliseconds)
window_shift: 0.010 #in seconds (10 milliseconds)

#training configuration
enroll_sessions: 3 #number of sessions to be included in the training set
test_sessions: 5   #number of sessions to be included in the test set

#preprocessing configurations
sampling_rate: 16000
bit_precision: 16
no_channels: 2

#UBM configuration
num_gaussians: 64

#i-vectors
batch_size: 30 #size of data batch
tv_rank: 25 # Rank of the total variability matrix
tv_iterations: 50 # number of iterations to train the variability matrix
scoring: cosine #can be either "cosine", or "mahalanobis"

#i-vectors (PLDA) configurations (depends on TV configuration)
enable_plda: no

#plotting configuration
DET_curve: rocch


